version: '3.1'

services:

  db:
    container_name: go-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
    volumes: 
      - ./sql-entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
